UNWIND [ {id:'ing_apple', canonical:'apple', category:'fruit'}, 
{id:'ing_asparagus', canonical:'asparagus', category:'vegetable'}, 
{id:'ing_avocado', canonical:'avocado', category:'fruit'}, 
{id:'ing_banana', canonical:'banana', category:'fruit'}, 
{id:'ing_bell_pepper', canonical:'bell pepper', category:'vegetable', alt:['capsicum','sweet pepper']}, 
{id:'ing_bitter_gourd', canonical:'bitter gourd', category:'vegetable'}, 
{id:'ing_bok_choy', canonical:'bok choy', category:'vegetable'}, 
{id:'ing_broccoli', canonical:'broccoli', category:'vegetable'}, 
{id:'ing_cabbage', canonical:'cabbage', category:'vegetable'}, 
{id:'ing_carrot', canonical:'carrot', category:'vegetable'}, 
{id:'ing_cashew', canonical:'cashew', category:'nut', allergen:true}, 
{id:'ing_cauliflower', canonical:'cauliflower', category:'vegetable'}, 
{id:'ing_chayote', canonical:'chayote', category:'vegetable'}, 
{id:'ing_chicken_breast', canonical:'chicken breast', category:'meat'}, 
{id:'ing_chicken_thigh', canonical:'chicken thigh', category:'meat'}, 
{id:'ing_chicken_wing', canonical:'chicken wing', category:'meat'}, 
{id:'ing_chili', canonical:'chili', category:'spice', alt:['chilli','chile']}, 
{id:'ing_coconut', canonical:'coconut', category:'fruit', alt:['coconuts']}, 
{id:'ing_corn', canonical:'corn', category:'grain', alt:['maize']}, 
{id:'ing_crab', canonical:'crab', category:'seafood', allergen:true}, 
{id:'ing_cucumber', canonical:'cucumber', category:'vegetable'},
{id:'ing_egg', canonical:'egg', category:'dairy', allergen:true, alt:['egg_']}, 
{id:'ing_eggplant', canonical:'eggplant', category:'vegetable', alt:['aubergine']}, 
{id:'ing_garlic', canonical:'garlic', category:'spice', alt:['garlic clove','garlic cloves']}, 
{id:'ing_ginger', canonical:'ginger', category:'spice'}, 
{id:'ing_grapes', canonical:'grapes', category:'fruit'}, 
{id:'ing_lemon', canonical:'lemon', category:'fruit'}, 
{id:'ing_lettuce', canonical:'lettuce', category:'vegetable'}, 
{id:'ing_lobster_tails', canonical:'lobster tails', category:'seafood'}, 
{id:'ing_mango', canonical:'mango', category:'fruit'}, 
{id:'ing_melon', canonical:'melon', category:'fruit'}, 
{id:'ing_milk', canonical:'milk', category:'dairy', allergen:true}, 
{id:'ing_onion', canonical:'onion', category:'vegetable', alt:['onions']}, 
{id:'ing_orange', canonical:'orange', category:'fruit'}, 
{id:'ing_oysters', canonical:'oysters', category:'seafood', allergen:true}, 
{id:'ing_pawpaw', canonical:'pawpaw', category:'fruit', alt:['papaya']}, 
{id:'ing_peanuts', canonical:'peanuts', category:'nut', allergen:true}, 
{id:'ing_peas', canonical:'peas', category:'legume'}, 
{id:'ing_pepper', canonical:'pepper', category:'spice', alt:['peper']}, 
{id:'ing_pineapple', canonical:'pineapple', category:'fruit'}, 
{id:'ing_pork_belly', canonical:'pork belly', category:'meat'}, 
{id:'ing_potato', canonical:'potato', category:'vegetable', alt:['potatoes']}, 
{id:'ing_pumpkin', canonical:'pumpkin', category:'vegetable'}, 
{id:'ing_radishes', canonical:'radishes', category:'vegetable'}, 
{id:'ing_red_rice', canonical:'red rice', category:'grain'}, 
{id:'ing_salmon', canonical:'salmon', category:'seafood', allergen:true}, 
{id:'ing_sea_scallops', canonical:'sea scallops', category:'seafood', allergen:true}, 
{id:'ing_shrimp', canonical:'shrimp', category:'seafood', allergen:true}, 
{id:'ing_spinach', canonical:'spinach', category:'vegetable'}, 
{id:'ing_strawberry', canonical:'strawberry', category:'fruit'}, 
{id:'ing_sweet_potato', canonical:'sweet potato', category:'vegetable'},
{id:'ing_tempeh', canonical:'tempeh', category:'plant_protein'}, 
{id:'ing_tofu', canonical:'tofu', category:'plant_protein'}, 
{id:'ing_tomato', canonical:'tomato', category:'vegetable', alt:['tomatoes']}, 
{id:'ing_tuna', canonical:'tuna', category:'seafood', allergen:true}, 
{id:'ing_white_rice', canonical:'white rice', category:'grain'}, 
{id:'ing_orange', canonical:'orange', category:'fruit'},
{id:'ing_oysters', canonical:'oysters', category:'seafood', allergen:true},
{id:'ing_pawpaw', canonical:'pawpaw', category:'fruit', alt:['papaya']},
{id:'ing_peanuts', canonical:'peanuts', category:'nut', allergen:true},
{id:'ing_peas', canonical:'peas', category:'legume'},
{id:'ing_pepper', canonical:'pepper', category:'spice', alt:['peper']},
{id:'ing_pineapple', canonical:'pineapple', category:'fruit'},
{id:'ing_pork_belly', canonical:'pork belly', category:'meat'},
{id:'ing_potato', canonical:'potato', category:'vegetable', alt:['potatoes']},
{id:'ing_pumpkin', canonical:'pumpkin', category:'vegetable'},
{id:'ing_radishes', canonical:'radishes', category:'vegetable'},
{id:'ing_red_rice', canonical:'red rice', category:'grain'},
{id:'ing_salmon', canonical:'salmon', category:'seafood', allergen:true},
{id:'ing_sea_scallops', canonical:'sea scallops', category:'seafood', allergen:true},
{id:'ing_shrimp', canonical:'shrimp', category:'seafood', allergen:true},
{id:'ing_spinach', canonical:'spinach', category:'vegetable'},
{id:'ing_strawberry', canonical:'strawberry', category:'fruit'},
{id:'ing_sweet_potato', canonical:'sweet potato', category:'vegetable'},
{id:'ing_tempeh', canonical:'tempeh', category:'plant_protein'},
{id:'ing_tofu', canonical:'tofu', category:'plant_protein'},
{id:'ing_tomato', canonical:'tomato', category:'vegetable', alt:['tomatoes']},
{id:'ing_tuna', canonical:'tuna', category:'seafood', allergen:true},
{id:'ing_white_rice', canonical:'white rice', category:'grain'}
] AS ing MERGE (i:Ingredient {ingredient_id: ing.id}) 
SET i.canonical_name = ing.canonical, 
i.category = ing.category, 
i.allergen_flag  = coalesce(ing.allergen,false),
i.alt_names = coalesce(ing.alt, []);